// apps/traffic-sign-tool/app/_components/links/ExternalLink.tsx
import { linkStyle } from './linkStyles'

type Props = { href?: string; className?: string; blank?: boolean; children: React.ReactNode }

export const ExternalLink = ({ href, className, blank, children }: Props) => {
  const target = blank ? '_blank' : undefined

  return (
    <a href={href} className={className || linkStyle} target={target} rel="noreferrer">
      {children}
    </a>
  )
}

// src/components/links/ExternalLink.svelte
<script lang="ts">
	import { linkStyle } from './linkStyles'

	export let href: string | undefined = undefined
	export let className: string | undefined = linkStyle
	export let blank = false
	const target = blank ? '_blank' : undefined
</script>

<a {href} class={className} {target} rel="noreferrer">
	<slot />
</a>
