// src/components/wiki/Tag.svelte
<script lang="ts">
	import WikiLinkKey from './WikiLinkKey.svelte'
	import WikiLinkValue from './WikiLinkValue.svelte'

	export let key: string
	export let value: string | string[]
</script>

<code
	><WikiLinkKey osmKey={key} /><span class="mx-0.5 text-gray-500">=</span><WikiLinkValue
		osmKey={key}
		osmValue={value}
	/></code
>

// app/_components/wiki/Tag.tsx
import { WikiLinkKey } from './WikiLinkKey'
import { WikiLinkValue } from './WikiLinkValue'

type Props = {
  tagKey: string
  tagValue: string | string[]
}

export const Tag = ({ tagKey, tagValue }: Props) => {
  return (
    <code>
      <WikiLinkKey osmKey={tagKey} />
      <span className="mx-0.5 text-gray-500">=</span>
      <WikiLinkValue osmKey={tagKey} osmValue={tagValue} />
    </code>
  )
}
