// _OLD/src/components/wiki/WikiLinkKey.svelte
<script lang="ts">
	import ExternalLink from '../links/ExternalLink.svelte'

	export let osmKey: string
	export let lang: 'DE' | 'US' = 'DE'

	const wikiLink = 'https://wiki.openstreetmap.org/wiki/'
	const splitKeys: string[] = osmKey.split(':')

	const links = splitKeys.map((keyPart) => {
		const link = `${wikiLink}${lang}:Key:${keyPart}`
		return {
			link,
			keyPart
		}
	})
</script>

{#each links as { link, keyPart }, index}
	<ExternalLink
		href={link}
		className="underline underline-offset-4 hover:decoration-1 decoration-transparent hover:decoration-stone-400"
		blank>{keyPart}</ExternalLink
	>{#if index < links.length - 1}:{/if}
{/each}

// apps/traffic-sign-tool/app/(signs)/_components/wiki/WikiLinkKey.tsx
import { ExternalLink } from '@app/app/_components/links/ExternalLink'

type Props = {
  osmKey: string
  lang?: 'DE' | 'US'
}

export const WikiLinkKey = ({ osmKey, lang = 'DE' }: Props) => {
  const wikiLink = 'https://wiki.openstreetmap.org/wiki/'
  const splitKeys: string[] = osmKey.split(':')

  const links = splitKeys.map((keyPart) => {
    const link = `${wikiLink}${lang}:Key:${keyPart}`
    return {
      link,
      keyPart,
    }
  })

  return (
    <>
      {links.map(({ link, keyPart }, index) => (
        <ExternalLink
          key={index}
          href={link}
          className="underline decoration-transparent underline-offset-4 hover:decoration-stone-400 hover:decoration-1"
          blank
        >
          {keyPart}
          {index < links.length - 1 && ':'}
        </ExternalLink>
      ))}
    </>
  )
}
