// src/components/wiki/WikiLinkValue.svelte
<script lang="ts">
	import ExternalLink from '../links/ExternalLink.svelte'

	export let osmKey: string
	export let osmValue: string | string[]
	export let lang: 'DE' | 'US' = 'DE'

	const wikiLink = 'https://wiki.openstreetmap.org/wiki/'

	function prepareLinks(values: string[]) {
		return values.map((valuePart) => {
			const link = `${wikiLink}${lang}:Tag:${osmKey}=${valuePart}`
			return {
				link,
				valuePart
			}
		})
	}

	const orLinks = typeof osmValue === 'object' ? prepareLinks(osmValue) : []
	const semiLinks = typeof osmValue === 'string' ? prepareLinks(osmValue.split(';')) : []
</script>

{#each orLinks as { link, valuePart }, index}
	<ExternalLink
		href={link}
		className="underline underline-offset-4 hover:decoration-1 decoration-transparent hover:decoration-stone-400"
		blank>{valuePart}</ExternalLink
	>{#if index < orLinks.length - 1}{' '}<em>or</em> {/if}
{/each}{#each semiLinks as { link, valuePart }, index}
	<ExternalLink
		href={link}
		className="underline underline-offset-4 hover:decoration-1 decoration-transparent hover:decoration-stone-400"
		blank>{valuePart}</ExternalLink
	>{#if index < semiLinks.length - 1};{/if}
{/each}

// apps/traffic-sign-tool/app/(signs)/_components/wiki/WikiLinkValue.tsx
import { ExternalLink } from '@app/app/_components/links/ExternalLink'
import { useCountryPrefixWithFallback } from '../store/CountryPrefixContext'

type Props = {
  osmKey: string
  osmValue: string | string[]
}

const wikiLink = 'https://wiki.openstreetmap.org/wiki'

export const wikiLinkClasses =
  'underline decoration-transparent underline-offset-4 hover:decoration-stone-400 hover:decoration-1'

export const WikiLinkValue = ({ osmKey, osmValue }: Props) => {
  const { countryPrefix } = useCountryPrefixWithFallback()

  function prepareLinks(values: string[] | undefined) {
    if (!values) return []
    return values.map((valuePart) => {
      const link = `${wikiLink}/${countryPrefix}:Tag:${osmKey}=${valuePart}`

      return {
        link,
        valuePart,
      }
    })
  }

  const orLinks = typeof osmValue === 'string' ? [] : prepareLinks(osmValue)
  const semiLinks = typeof osmValue === 'string' ? prepareLinks(osmValue.split(';')) : []

  return (
    <>
      {orLinks.map(({ link, valuePart }, index) => (
        <span key={index}>
          <ExternalLink href={link} className={wikiLinkClasses} blank>
            {valuePart}
          </ExternalLink>
          {index < orLinks.length - 1 && (
            <>
              {' '}
              <em>or</em>{' '}
            </>
          )}
        </span>
      ))}
      {semiLinks.map(({ link, valuePart }, index) => (
        <span key={index}>
          <ExternalLink href={link} className={wikiLinkClasses} blank>
            {valuePart}
          </ExternalLink>
          {index < semiLinks.length - 1 && ';'}
        </span>
      ))}
    </>
  )
}
